// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgAlqlZn0f-NjqZamOMZ4hQU7rYOdP5xw',
    appId: '1:731367190580:web:62bdd619ed719a1892da61',
    messagingSenderId: '731367190580',
    projectId: 'personal-finance-app-355cb',
    authDomain: 'personal-finance-app-355cb.firebaseapp.com',
    storageBucket: 'personal-finance-app-355cb.firebasestorage.app',
    measurementId: 'G-YLQ4PSJHV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBY4UvNCVvXJG9lE5DPbbdg7pE9948KA',
    appId: '1:731367190580:android:cd310b9cc09c054b92da61',
    messagingSenderId: '731367190580',
    projectId: 'personal-finance-app-355cb',
    storageBucket: 'personal-finance-app-355cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6iil5R3V_L7D3kNP9Va5ugaG5CgsRlUU',
    appId: '1:731367190580:ios:208bd7d2682dd56c92da61',
    messagingSenderId: '731367190580',
    projectId: 'personal-finance-app-355cb',
    storageBucket: 'personal-finance-app-355cb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6iil5R3V_L7D3kNP9Va5ugaG5CgsRlUU',
    appId: '1:731367190580:ios:208bd7d2682dd56c92da61',
    messagingSenderId: '731367190580',
    projectId: 'personal-finance-app-355cb',
    storageBucket: 'personal-finance-app-355cb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgAlqlZn0f-NjqZamOMZ4hQU7rYOdP5xw',
    appId: '1:731367190580:web:da0ce48a50ad92e892da61',
    messagingSenderId: '731367190580',
    projectId: 'personal-finance-app-355cb',
    authDomain: 'personal-finance-app-355cb.firebaseapp.com',
    storageBucket: 'personal-finance-app-355cb.firebasestorage.app',
    measurementId: 'G-N6C8918S5T',
  );
}
